[package]
name = "rust-minimatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.266.0"
serde = "1.0.197"

[dev-dependencies]
tokio = { version = "1.36.0", features = ["macros"] }
